config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'home' => 'contracts#index'
  
  resources :items
  resources :commodities
  resources :sizes
  resources :varieties
  resources :grades
  resources :accounts
  resources :users
  resources :sessions
  resources :orders
  resources :invoices
  resources :origins
  resources :terms
  resources :remarks
  resources :delivery_locations
  resources :shipping_instructions, only: [:show]
  resources :packing_lists, only: [:show]
  resources :certificate_of_origins  
  resources :fumigations  

  get 'contracts/:id/contract_report' => 'contracts#contract_report', as: :contract_report
  get 'invoices/:id/invoice_report' => 'invoices#invoice_report', as: :invoice_report 
  get 'orders/:id/shipping_report' => 'orders#shipping_report', as: :shipping_report
  get 'contracts/:id/contract_doc' => 'contracts#contract_doc', as: :contract_doc
  get 'contracts/:id/broker_contract_doc' => 'contracts#broker_contract_doc', as: :broker_contract_doc
  
  get 'ajax/item_names' => 'ajax#item_names', as: :item_names
  get 'ajax/filter_items_by_variety' => 'ajax#filter_items_by_variety', as: :filter_items_by_variety

  resources :documents
  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destroy'
  get 'ui(/:action)', controller: 'ui'
  resources :contracts do
    resource :orders
  end

  resources :orders do 
    resource :certificate_of_origins
  end
  

end

app/models/certificate_of_origin.rb
class CertificateOfOrigin < ActiveRecord::Base
  belongs_to :order
  validates_presence_of :order
  validates_presence_of :forwarding_agent
end

app/controllers/certificate_of_origins_controller.rb
class CertificateOfOriginsController < ApplicationController
  before_filter :require_user
  
  def new
    @certificate_of_origin = CertificateOfOrigin.new(order_id: params[:order_id])
    render :new
  end

  def edit
    @certificate_of_origin = CertificateOfOrigin.find(params[:id])
    render :edit  
  end

  def create
    @certificate_of_origin = CertificateOfOrigin.new(certificate_of_origins_params)
    if @certificate_of_origin.save
      flash[:success] = "Updated"
      redirect_to edit_certificate_of_origin_path(@certificate_of_origin)
    else
      flash[:error] = @certificate_of_origin.errors.full_messages
      render :new
    end
  end

  def update
    @certificate_of_origin = CertificateOfOrigin.find(params[:id])
    if @certificate_of_origin.update(certificate_of_origins_params)
      flash[:success] = "Updated"
      redirect_to edit_certificate_of_origin_path(@certificate_of_origin)
    else
      render :edit
    end
  end

  def show
    @order = CertificateOfOrigin.find(params[:id]).order 
    respond_to do |format|
      format.docx do
        report = CertificateOfOriginDoc.new(@order)
        # Respond to the request by sending the temp file
        send_file report.create_report, filename: "certificate_of_origin.docx", disposition: 'inline'
      end
    end
  end

  private

  def certificate_of_origins_params
    params.require(:certificate_of_origin).permit(
      :treatment,
      :place_of_initial_receipt,
      :forwarding_agent,
      :initial_carriage_by,
      :vessel,
      :hs_code,
      :order_id,
      :routing_instructions,
      :port_of_loading
      )
  end
end

app/views/certificate_of_origins/_form.html.haml
%div#content
  -# widget grid -->
  %section#widget-grid
    -# row -->
    %div.row
      -# NEW WIDGET START -->
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        -#- end widget -->
        -#- Widget ID (each widget will need unique ID)-->
        %div.jarviswidget.jarviswidget-color-blueDark#remarki{ "data-widget-editbutton" => "false" }
          %header
            %span.widget-icon
              %i.fa.fa-table
            %h2.widget-header Certificate of Origin
          -#- widget div-->
          %div
            -# widget edit box -->
            %div.jarviswidget-editbox
              -# This area used as dropdown edit box -->
            -#- end widget edit box -->
            -#- widget content -->
            %div.widget-body.no-padding
              = bootstrap_form_for(@certificate_of_origin, class: "login-form smart-form client-form", layout: :horizontal, label_errors: true, remote: true) do |f|

                %div.well.well-sm.bg-color-darken.txt-color-white.no-border#button-header
                  = link_to edit_contract_path(@certificate_of_origin.order.contract), remote: true, class: "btn btn-info", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..."} do 
                    %i.fa.fa-lg.fa-fw.fa-pencil-square-o
                    %span.menu-item-parent 
                      = "Contract - #{@certificate_of_origin.order.contract.seller_contract}"

                  = link_to edit_order_path(@certificate_of_origin.order), remote: true, class: "btn btn-info", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..."} do 
                    %i.fa.fa-lg.fa-fw.fa-truck
                    %span.menu-item-parent 
                      = "Load - #{@certificate_of_origin.order.row_on_contract}"

                  = button_tag(type: 'submit', class: "btn btn-primary") do
                    %i.fa.fa-lg.fa-fw.fa-save
                    %span Save


                  - unless @certificate_of_origin.new_record?
                    = link_to certificate_of_origin_path(@certificate_of_origin, format: "docx"), target: "_blank", class: "btn btn-default", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..."} do 
                      %i.fa.fa-lg.fa-fw.fa-cloud-download
                      %span.menu-item-parent Certificate Of Origin 

                  %span.pull-right
                    %em.text-info= "Seller: #{@certificate_of_origin.order.contract.seller.name}"
                    %br
                    %em.text-info= "Buyer: #{@certificate_of_origin.order.contract.buyer.name}"
                    %br
                    %em.text-muted= "Load #{@certificate_of_origin.order.row_on_contract} of #{@certificate_of_origin.order.contract.orders.count}"
                %div.well
                  = f.hidden_field :order_id
                  = f.text_field :hs_code
                  = f.text_field :treatment
                  = f.text_field :place_of_initial_receipt
                  = f.text_field :forwarding_agent
                  = f.text_field :initial_carriage_by
                  = f.text_field :port_of_loading
                  = f.text_field :vessel
                  = f.text_area :routing_instructions

app/views/certificate_of_origins/edit.js.erb
$('#content').replaceWith( '<%= j render "form", certificate_of_origin: @certificate_of_origin %>');
pageSetUp();

<% if flash.any? %>
  $('#content').before('<%= j render("shared/messages") %>');
<% end %>

setTimeout(function() {
  $('.flash-messages').remove();
}, 10000);