config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'home' => 'contracts#index'
  
  resources :items
  resources :commodities
  resources :sizes
  resources :varieties
  resources :grades
  resources :accounts
  resources :users
  resources :sessions
  resources :orders
  resources :invoices
  resources :origins
  resources :terms
  resources :remarks
  resources :delivery_locations
  resources :shipping_instructions, only: [:show]
  resources :packing_lists, only: [:show]
  resources :certificate_of_origins  
  resources :fumigations  

  get 'contracts/:id/contract_report' => 'contracts#contract_report', as: :contract_report
  get 'invoices/:id/invoice_report' => 'invoices#invoice_report', as: :invoice_report 
  get 'orders/:id/shipping_report' => 'orders#shipping_report', as: :shipping_report
  get 'contracts/:id/contract_doc' => 'contracts#contract_doc', as: :contract_doc
  get 'contracts/:id/broker_contract_doc' => 'contracts#broker_contract_doc', as: :broker_contract_doc
  
  get 'ajax/item_names' => 'ajax#item_names', as: :item_names
  get 'ajax/filter_items_by_variety' => 'ajax#filter_items_by_variety', as: :filter_items_by_variety

  resources :documents
  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destroy'
  get 'ui(/:action)', controller: 'ui'
  resources :contracts do
    resource :orders
  end

  resources :orders do 
    resource :certificate_of_origins
  end
  

end

app/views/shared/_data_table.html.haml
%div#content
  -# widget grid -->
  %section#widget-grid
    -# row -->
    %div.row
      -# NEW WIDGET START -->
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        %div.jarviswidget.jarviswidget-color-blueDark{ "data-widget-editbutton" => "true", "data-widget-deletebutton" => "false", "data-widget-togglebutton" => "false", "data-widget-fullscreenbutton" => "false", "data-widget-colorbutton" => "false" }
          %header
            %span.widget-icon
              %i.fa.fa-table
            - if data.first
              %h2.widget-header= "#{data.first.class.name} List"
          -#- widget div-->
          %div
            -# widget edit box -->
            %div.jarviswidget-editbox
              -# This area used as dropdown edit box -->
            -#- end widget edit box -->
            -#- widget content -->
            %div.widget-body
              %div.widget-body-toolbar
                - if data.first
                  = link_to new_polymorphic_path(data.first), class: "btn btn-success", remote: true do 
                    %i.fa.fa-plus
                    %span= "New #{data.first.class.name}"

              %table#recordTable.table.table-striped.table-bordered.table-hover{ :width => "100%" }
                %thead
                  %tr
                    %th ID
                    %th Name
                %tbody
                  - data.each do |record|
                    %tr
                      %td= record.id
                      %td
                        = link_to record.name, edit_polymorphic_path(record), remote: true

app/views/shared/_header.html.haml
%header#header
  %div#logo-group
    -# PLACE YOUR LOGO HERE -->
    %span#logo
      -#=image_tag 'logo.png', alt: "BKISystem"
      =image_tag 'bki_logo.png', class: "img-responsive", id: "logo-image"
      %small BKI Systems

app/views/shared/_leftside.html.haml
-# Left panel : Navigation area -->
-# Note: This width of the aside area can be adjusted through LESS variables -->
%aside#left-panel
  -#- User info -->
  %div.login-info
    %span
      = link_to edit_user_path(current_user.id), remote: true do
        = current_user.name
        %i.fa.fa-lg.fa-fw.fa-gear

  -# end user info -->

  -#- NAVIGATION : This navigation is also responsive-->
  %nav#leftnav
    %ul
      %li.nav-item
        = link_to contracts_path, remote: true do 
          %i.fa.fa-lg.fa-fw.fa-pencil-square-o
          %span.menu-item-parent Contracts
      %li.nav-item
        = link_to orders_path, remote: true do 
          %i.fa.fa-lg.fa-fw.fa-truck
          %span.menu-item-parent Loads     
      %li.nav-item
        = link_to invoices_path, remote: true do 
          %i.fa.fa-lg.fa-fw.fa-money
          %span.menu-item-parent Invoices      


      %li.nav-item
        %a{ :href => "#" }
          %i.fa.fa-lg.fa-fw.fa-cubes
          %span.menu-item-parent Item Master
        %ul
          -#%li.nav-item
            -#= link_to 'New Contract', new_contract_path, remote: true
          %li.nav-item
            = link_to 'Items', items_path, remote: true
          %li.nav-item
            = link_to 'Commodities', commodities_path, remote: true
          %li.nav-item
            = link_to 'Origins', origins_path, remote: true
          %li.nav-item
            = link_to 'Sizes', sizes_path, remote: true
          %li.nav-item
            = link_to 'Varieties', varieties_path, remote: true
          %li.nav-item
            = link_to 'Grades', grades_path, remote: true
      %li.nav-item
        = link_to accounts_path, remote: true do 
          %i.fa.fa-lg.fa-fw.fa-university
          %span Accounts
      %li.nav-item
        = link_to users_path, remote: true do
          %i.fa.fa-lg.fa-fw.fa-users        
          %span.menu-item-parent Users
      %li.nav-item
        %a{ :href => "#" }
          %i.fa.fa-lg.fa-fw.fa-gear
          %span.menu-item-parent Table Maintenance
        %ul
          -#%li.nav-item
            -#= link_to 'New Contract', new_contract_path, remote: true
          %li.nav-item
            = link_to 'Terms', terms_path, remote: true
          %li.nav-item
            = link_to 'Remarks', remarks_path, remote: true
          %li.nav-item
            = link_to 'Delivery Locations', delivery_locations_path, remote: true
          %li.nav-item
            = link_to 'Documents', documents_path, remote: true 
      %li.nav-item
        = link_to sign_out_path do
          %i.fa.fa-sign-out
          %span Sign Out

app/views/shared/_logout.html.haml
%div.divMessageBox.animated.fadeIn.fast#MsgBoxBack
  %div.MessageBoxContainer.animated.fadeIn.fast#Msg1
    %div.MessageBoxMiddle
      %span.MsgTitle
        %i.fa.fa-sign-out.txt-color-orangeDark
        Logout
        %span.txt-color-orangeDark
          %strong
            john.doe 
          ?
      %p.pText
        You can improve your security further after logging out by closing this opened browser
      %div.MessageBoxButtonSection
        %button#bot1-Msg1.btn.btn-default.btn-sm.botTempo
          No
        %button#bot2-Msg1.btn.btn-default.btn-sm.botTempo
          Yes

app/views/shared/_messages.html.haml
- flash.each do |type, msg|
  %div.flash-messages.fade.in.alert{ :class => "#{bootstrap_class_for(type)}" }
    %button.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{type}" if msg.is_a?(String)
  - flash.discard

app/views/shared/_ribbon.html.haml
%div#ribbon
  %span.ribbon-button-alignment


  -#- You can also add more buttons to the
  -#ribbon for further usability
  -#
  -#Example below:
  -#
  %span.ribbon-button-alignment.pull-right
  -#%span#search.btn.btn-ribbon.hidden-xs{ "data-title" => "search" }
  -#  %i.fa-grid 
  -#  Change Grid
  -#%span#add.btn.btn-ribbon.hidden-xs.pull-right{ "data-title" => "add" }
  -#  %i.fa-plus
  -#  Add
  -#%span#search.btn.btn-ribbon{ "data-title" => "search" }
  -#  %i.fa-search
  -#  %span.hidden-mobile Search
  -#</span> -->

app/views/shared/_update_data.html.haml
%div#content
  -# widget grid -->
  %section#widget-grid
    -# row -->
    %div.row
      -# NEW WIDGET START -->
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        %div.jarviswidget.jarviswidget-color-blueDark{ "data-widget-editbutton" => "true", "data-widget-deletebutton" => "false", "data-widget-togglebutton" => "false", "data-widget-fullscreenbutton" => "false", "data-widget-colorbutton" => "false" }
          %header
            %span.widget-icon
              %i.fa.fa-table
            %h2.widget-header= data_object.name
          -#- widget div-->
          %div
            -# widget edit box -->
            %div.jarviswidget-editbox
              -# This area used as dropdown edit box -->
            -#- end widget edit box -->
            -#- widget content -->
            %div.widget-body.no-padding
              = bootstrap_form_for(data_object, label_errors: true, remote: true) do |f|
                = f.text_field :name
                = f.submit data_object.new_record? ? "Add" : "Update"