config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'home' => 'contracts#index'
  
  resources :items
  resources :commodities
  resources :sizes
  resources :varieties
  resources :grades
  resources :accounts
  resources :users
  resources :sessions
  resources :orders
  resources :invoices
  resources :origins
  resources :terms
  resources :remarks
  resources :delivery_locations
  resources :shipping_instructions, only: [:show]
  resources :packing_lists, only: [:show]
  resources :certificate_of_origins  
  resources :fumigations  

  get 'contracts/:id/contract_report' => 'contracts#contract_report', as: :contract_report
  get 'invoices/:id/invoice_report' => 'invoices#invoice_report', as: :invoice_report 
  get 'orders/:id/shipping_report' => 'orders#shipping_report', as: :shipping_report
  get 'contracts/:id/contract_doc' => 'contracts#contract_doc', as: :contract_doc
  get 'contracts/:id/broker_contract_doc' => 'contracts#broker_contract_doc', as: :broker_contract_doc
  
  get 'ajax/item_names' => 'ajax#item_names', as: :item_names
  get 'ajax/filter_items_by_variety' => 'ajax#filter_items_by_variety', as: :filter_items_by_variety

  resources :documents
  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destroy'
  get 'ui(/:action)', controller: 'ui'
  resources :contracts do
    resource :orders
  end

  resources :orders do 
    resource :certificate_of_origins
  end
  

end

app/models/fumigation.rb
class Fumigation < ActiveRecord::Base
  belongs_to :order
end

app/controllers/fumigations_controller.rb
class FumigationsController < ApplicationController
  before_filter :require_user
  
  def new
    @fumigation = Fumigation.new(order_id: params[:order_id])
    render :new
  end

  def edit
    @fumigation = Fumigation.find(params[:id])
    render :edit  
  end

  def create
    @fumigation = Fumigation.new(fumigation_params)
    if @fumigation.save
      flash[:success] = "Updated"
      redirect_to edit_fumigation_path(@fumigation)
    else
      flash[:error] = @fumigation.errors.full_messages
      render :new
    end
  end

  def update
    @fumigation = Fumigation.find(params[:id])
    if @fumigation.update(fumigation_params)
      flash[:success] = "Updated"
      redirect_to edit_fumigation_path(@fumigation)
    else
      render :edit
    end
  end

  def show
    @order = Fumigation.find(params[:id]).order 
    respond_to do |format|
      format.docx do
        report = FumigationDoc.new(@order)
        # Respond to the request by sending the temp file
        send_file report.create_report, filename: "fumigation.docx", disposition: 'inline'
      end
    end
  end

  private

  def fumigation_params
    params.require(:fumigation).permit(
      :treatment,
      :duration_of_exposure,
      :temperature,
      :hs_code,
      :date_of_treatment,
      :concentration,
      :order_id,
      :notes,
      :permit_number
      )
  end
end

app/views/fumigations/_form.html.haml
%div#content
  -# widget grid -->
  %section#widget-grid
    -# row -->
    %div.row
      -# NEW WIDGET START -->
      %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
        -#- end widget -->
        -#- Widget ID (each widget will need unique ID)-->
        %div.jarviswidget.jarviswidget-color-blueDark#remarki{ "data-widget-editbutton" => "false" }
          %header
            %span.widget-icon
              %i.fa.fa-table
            %h2.widget-header Fumigation
          -#- widget div-->
          %div
            -# widget edit box -->
            %div.jarviswidget-editbox
              -# This area used as dropdown edit box -->
            -#- end widget edit box -->
            -#- widget content -->
            %div.widget-body.no-padding
              = bootstrap_form_for(@fumigation, class: "login-form smart-form client-form", layout: :horizontal, label_errors: true, remote: true) do |f|

                %div.well.well-sm.bg-color-darken.txt-color-white.no-border#button-header
                  = link_to edit_contract_path(@fumigation.order.contract), remote: true, class: "btn btn-info", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..."} do 
                    %i.fa.fa-lg.fa-fw.fa-pencil-square-o
                    %span.menu-item-parent 
                      = "Contract - #{@fumigation.order.contract.seller_contract}"

                  = link_to edit_order_path(@fumigation.order), remote: true, class: "btn btn-info", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..." } do 
                    %i.fa.fa-lg.fa-fw.fa-truck
                    %span.menu-item-parent 
                      = "Load - #{@fumigation.order.row_on_contract}"

                  = button_tag(type: 'submit', class: "btn btn-primary") do
                    %i.fa.fa-lg.fa-fw.fa-save
                    %span Save


                  - unless @fumigation.new_record?
                    = link_to fumigation_path(@fumigation, format: "docx"), target: "_blank", class: "btn btn-default", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading..." } do 
                      %i.fa.fa-lg.fa-fw.fa-cloud-download
                      %span.menu-item-parent Fumigation 

                  %span.pull-right
                    %em.text-info= "Seller: #{@fumigation.order.contract.seller.name}"
                    %br
                    %em.text-info= "Buyer: #{@fumigation.order.contract.buyer.name}"
                    %br
                    %em.text-muted= "Load #{@fumigation.order.row_on_contract} of #{@fumigation.order.contract.orders.count}"
                %div.well
                  = f.hidden_field :order_id
                  = f.text_field :treatment
                  = f.text_field :duration_of_exposure
                  = f.text_field :temperature
                  = f.text_field :hs_code
                  = f.date_field :date_of_treatment
                  = f.text_field :concentration
                  = f.text_field :permit_number
                  = f.text_area :notes

app/views/fumigations/edit.js.erb
$('#content').replaceWith( '<%= j render "form", fumigation: @fumigation %>');
pageSetUp();

<% if flash.any? %>
  $('#content').before('<%= j render("shared/messages") %>');
<% end %>

setTimeout(function() {
  $('.flash-messages').remove();
}, 10000);

app/views/fumigations/new.js.erb
$('#content').replaceWith( '<%= j render("form") %>');
pageSetUp();

<% if flash.any? %>
  $('#content').before('<%= j render("shared/messages") %>');
<% end %>

setTimeout(function() {
  $('.flash-messages').remove();
}, 10000);